# -*- coding: utf-8 -*-
"""Transformação de Distância.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oG215b8EPXaxFZxDeVafzXPXUxk0Gt9M
"""

import numpy as np
from scipy.ndimage import distance_transform_edt, label
from skimage.measure imimportport regionprops

def calculate_distance_transform(binary_image):

    distance_map = distance_transform_edt(binary_image)
    return distance_map

def extract_metric(labeled_image):

    regions = regionprops(labeled_image)
    metrics = []

    for region in regions:
        comp_metrics = {
            'label': region.label,
            'area': region.area,
            'perimeter': region.perimeter,
            'centroid': region.centroid  # (row, col) format
        }
        metrics.append(comp_metrics)

    return metrics


if __name__ == "__main__":

    binary_image = np.array([
        [0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1],
        [0, 0, 0, 1, 1],
        [1, 1, 0, 0, 0]
    ], dtype=bool)

    dist_map = calculate_distance_transform(binary_image)
    print(dist_map)

    labeled, num_labels = label(binary_image)
    print(f"Número de componentes rotulados: {num_labels}")

    metrics = extract_metric(labeled)
    for m in metrics:
        print(f"Componente: {m['label']}, Área: {m['area']}, Perímetro: {m['perimeter']:.2f}, Centróide: {m['centroid']}")